#!/bin/bash

make transmute_trees || exit 1

if [[ $# -lt 3 ]]; then
    echo -e 'usage: ./tt [total entries] ($@)\n'
    ./transmute_trees
    exit 1
fi

ENTRIES=$1
[ $ENTRIES -le 0 ] && {
    echo -e "error: negative total entries: $ENTRIES\n"; exit 1; }

SIZE=1024
SLICES=$(( ($ENTRIES - 1) / $SIZE ))

BASE=$(basename $3 .root)
for SLICE in $(seq 0 $SLICES ); do
    sem -j-4 --linebuffer \
            "./transmute_trees $2 ${3}.$SLICE \
            $(( $SLICE * $SIZE )) $(( ($SLICE + 1) * $SIZE )) ${@:4} \
            &> notes/log-tt-$BASE-$ENTRIES-${SLICE}.log; \
            echo \"   done: part $SLICE\""
done
sem --wait

hadd $3 ${3}.*
